archetypeDir = "archetypes"
assetDir = "assets"
baseURL = "https://nsynovic.dev"

buildDrafts = false
buildExpired = false
buildFuture = false

canonifyURLs = false
contentDir = "content"
copyright = "Nicholas M. Synovic"
dataDir = "data"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
disableAliases = false
disableHugoGeneratorInject = false
disableKinds = []
disableLiveReload = false
disablePathToLower = false
enableEmoji = true
enableGitInfo = true
enableMissingTranslationPlaceholders = false
enableRobotsTXT = true
googleAnalytics = ""
hasCJKLanguage = false
languageCode = "en-us"
newContentEditor = ""
noChmod = false
noTimes = false
paginate = 15
paginatePath = "page"
pluralizeListTitles = true
publishDir = "public"
relativeURLs = false
refLinksErrorLevel = "ERROR"
refLinksNotFoundURL = "https://nsynovic.dev"
removePathAccents = false
rssLimit = -1
sectionPagesMenu = "main"
summaryLength = 70
theme = "ananke-custom"
themesDir = "themes"
timeout = "30s"
timeZone = "UTC"
title = "Nicholas M. Synovic"
titleCaseStyle = "AP"
uglyURLs = false
watch = false

[menu]
[[menu.main]]
  identifier = 'Resume'
  name = 'Resume'
  pre = "<i class='fa fa-heart'></i>"
  url = 'https://github.com/NicholasSynovic/nsynovic.dev/raw/main/static/resumes/Nicholas_Synovic-Resume.pdf'
  weight = 0

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/nsynovic"
label = "Facebook"
color = "red"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/NicholasSynovic"
label = "GitHub"
color = "orange"

[[params.ananke_socials]]
name = "instagram"
url = "https://instagram.com/nicholas_synovic"
label = "Instagram"
color = "yellow"

[[params.ananke_socials]]
name = "linkedin"
url = "https://linkedin.com/in/nsynovic"
label = "LinkedIn"
color = "green"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/nick_synovic"
label = "Twitter"
color = "blue"

[[params.ananke_socials]]
name = "youtube"
url = "https://www.youtube.com/channel/UCVG2VYy7GJ86BLiUaj5LEZQ"
label = "YouTube Channel"
color = "indigo"
