archetypeDir = "archetypes"
assetDir = "assets"
baseURL = "https://nsynovic.dev"

buildDrafts = false
buildExpired = false
buildFuture = false

canonifyURLs = false
contentDir = "content"
copyright = "Nicholas M. Synovic"
dataDir = "data"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
disableAliases = false
disableHugoGeneratorInject = false
disableKinds = []
disableLiveReload = false
disablePathToLower = false
enableEmoji = true
enableGitInfo = true
enableMissingTranslationPlaceholders = false
enableRobotsTXT = true
googleAnalytics = ""
hasCJKLanguage = false
languageCode = "en-us"
newContentEditor = ""
noChmod = false
noTimes = false
paginate = 15
paginatePath = "page"
pluralizeListTitles = true
publishDir = "public"
relativeURLs = false
refLinksErrorLevel = "ERROR"
refLinksNotFoundURL = "https://nsynovic.dev"
removePathAccents = false
rssLimit = -1
sectionPagesMenu = "main"
summaryLength = 70
theme = "ananke-custom"
themesDir = "themes"
timeout = "30s"
timeZone = "UTC"
title = "Nicholas M. Synovic"
titleCaseStyle = "AP"
uglyURLs = false
watch = false

[[params.ananke_socials]]
name = "facebook"
url = "https://twitter.com/GoHugoIO"
label = "PENIS"
color = "gray"

[[params.ananke_socials]]
name = "github"
url = "https://twitter.com/GoHugoIO"
label = "PENIS"
color = "gray"

[[params.ananke_socials]]
name = "instagram"
url = "https://twitter.com/GoHugoIO"
label = "PENIS"
color = "gray"

[[params.ananke_socials]]
name = "linkedin"
url = "https://twitter.com/GoHugoIO"
label = "PENIS"
color = "gray"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
label = "PENIS"
color = "gray"

[[params.ananke_socials]]
name = "mastodon"
url = "https://twitter.com/GoHugoIO"
label = "PENIS"
color = "gray"

[[params.ananke_socials]]
name = "medium"
url = "https://twitter.com/GoHugoIO"
label = "PENIS"
color = "gray"

[[params.ananke_socials]]
name = "rss"
url = "https://twitter.com/GoHugoIO"
label = "PENIS"
color = "gray"

[[params.ananke_socials]]
name = "stackoverflow"
url = "https://twitter.com/GoHugoIO"
label = "PENIS"
color = "gray"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
label = "PENIS"
color = "gray"

[[params.ananke_socials]]
name = "youtube"
url = "https://twitter.com/GoHugoIO"
label = "PENIS"
color = "gray"
