exclude: 'archetypes'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: sort-simple-yaml
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.14  # Use the ref you want to point at
    hooks:
    - id: mdformat
      additional_dependencies:
      - mdformat-black
      - mdformat-gfm
      - mdformat-tables
      - mdformat-toc
      - mdformat-frontmatter
