title = "Nicholas M. Synovic"
baseURL = "https://nsynovic.dev"
languageCode = "en-us"
theme = "ananke"
# resourceDir = "./resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 15
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Nicholas M. Synovic"
  favicon = "/images/favicon.ico"
  # site_logo = "/images/android-chrome-192x192.png"
  description = "Researcher, Developer, Educator, Learner"
  background_color_class = "bg-mid-gray"
  recent_posts_number = 5
