text_color = ""
author = "Nicholas M. Synovic"
favicon = "/images/favicon.ico"
# site_logo = "/images/android-chrome-192x192.png"
description = "Researcher, Developer, Educator, Learner"
background_color_class = "bg-gray"
recent_posts_number = 5
